### ISSUE TITLE
Drop mp4creator support, make mp4box default

### ISSUE THREAD

**Issue by mshick** [gavinbeatty/mkvtomp4#10]
mpeg4-ip / mp4creator seems to be a dead project, while GPAC mp4box is being actively developed. Add in the fact that mp4box seems more readily available in package managers, and I feel mp4box is the way to go.

Plus, as I've been working on my various enhancements / PRs, I've realized the entire script can be improved significantly by standardizing on a single muxer.

If this direction is desired I'll submit a PR starting the process.

**Comment by tcurdt** [comment]
+1

**Comment by gavinbeatty** [comment]
That's probably sensible, and I think a fork has already done so. I've updated a few things recently to get it into a working state, but don't have time for further changes right now. If I get time to rewrite, I think I'll stick to MP4Box.

I had not used the project for years, so apologies for the delay.
