### ISSUE TITLE
Major overhaul

### ISSUE THREAD

**Issue by mshick** [gavinbeatty/mkvtomp4#11]
I've really been finding this script useful, but I found tons of features I wanted to add, and wasn't really able to separate them out cleanly at a point, so I've gone ahead and just made my [master](http://github.com/mshick/mkvtomp4) a complete collection of all the changes.

If you're interested in collaborating I can do a PR against your master, and you'd probably want to do a major version bump given all the changes. They include, "intelligent" audio and subtitles track selection, a faster implementation that builds flags for a single mp4box command (meaning, only one isotmp write), support for all major audio codecs (FLAC, VORBIS, DTS, AC3) and the concept of safety tracks, which is a little like the default Handbrake settings. 

I also brought in the idea of device feature profiles (again, Handbrake) allowing sets of features and formats to be defined, and then working the output into those parameters.

I hope to get burned subs working for PS3 at some point in the future.

If you're not as interested in doing the PR, then I'll probably rewrite the docs, try to figure out a snappy name, and go ahead with my own version.

My goal, basically, is to have a script that can conform mkvs to apple playable m4vs and will just run as a background process on my media server, no manual intervention whatsoever. So far, I think I've got it! 

This project has been a fantastic starting point -- I wouldn't have figured out that mp4 profile fix for ages!

**Comment by morberg** [comment]
Hi @mshick , is there a way to install your version with brew on OS X? Or do I need to download the files manually from github? It didn't seem like you set up a separate project yet.

I'm also wondering if your latest version supports taking subtitles srt format from the mkv and convert to tx3g format and embeds it in the mp4 file (ffpmeg has support for this by adding option '-c:s :mov_text').

**Comment by mshick** [comment]
@morberg You can tap my personal homebrew. `brew tap mshick/personal`. You'll then be able to install it using `brew install mshick/personal/mkvtomp4`. Also check out out a project I built on top of the fork, mshick/arrivals-osx, as it might be of interest.

I think what you're saying could be done. Not sure how soon I could get to it. Perhaps you can create an issue on my forked repo, and we can continue the discussion there? Don't want to hijack this project's issues.

**Comment by tcurdt** [comment]
@mshick does your fork support h265 (or others) yet? (see https://github.com/gpac/gpac/issues/291)

**Comment by gavinbeatty** [comment]
I had a quick look at your features and fixes, @mshick, great stuff! I have very modest needs for now, so I can't take the time to collaborate or merge your changes. But if my needs grow, I would strongly consider switching to become a user of yours.
