### ISSUE TITLE
h265 support

### ISSUE THREAD

**Issue by tcurdt** [gavinbeatty/mkvtomp4#12]
I am not sure if this project is entirely focused on h264 (as the description suggests) but I've run into an issue when I was trying to convert a h265 file. (see https://github.com/gpac/gpac/issues/291)

As it turns out `MP4box` detects the format from the file extension. If there is any chance it would be great to change `mkvtomp4` to honor this requirement and thereby support more than just h264.

If it could call

```
['MP4Box', '-add', 'foo.mkv.h265#video:trackID=1', '-hint', '-fps', '23.976', 'foo.mp4']
```

if necessary - that would be great.

(Note the `foo.mkv.h265` instead of `foo.mkv.h264`)

**Comment by cconcolato** [comment]
Note that MP4Box detects the type of data from the file extension or from parameters on the command line (like fmt=HEVC) and sometimes detects it from the content.

**Comment by tcurdt** [comment]
From the `gpac` guys it sounds that detection is not really an option.
So either it needs to be passed as `fmt` or use the appropriate extension.

**Comment by tcurdt** [comment]
Just to give it a try [I changed the extension to `.h265`](https://github.com/gavinbeatty/mkvtomp4/blob/master/simplemkv/tomp4.py#L267) and then conversion runs through. Unfortunately the resulting `mp4` seems to be broken/invalid:

    ffmpeg -v error -i foo.mp4 -f null - 2>error.log
    [hevc @ 0x7ff56280c200] PTL information for sublayer 0 too short
    [hevc @ 0x7ff56280c200] VPS 0 does not exist
    [hevc @ 0x7ff56280c200] SPS 0 does not exist.
    [hevc @ 0x7ff56280c200] PPS id out of range: 0
        Last message repeated 119 times
    [buffer @ 0x7ff561f000c0] Unable to parse option value "-1" as pixel format
        Last message repeated 1 times
    [buffer @ 0x7ff561f000c0] Error setting option pix_fmt to value -1.
    [graph 0 input from stream 0:0 @ 0x7ff561f00000] Error applying options to the filter.
    Error opening filters!

**Comment by jeanlf** [comment]
If you're using the same file as in gpac/gpac#291, it seems this file is not completely conformannt to HEVC (tested with HEVC HM soft, VPS is corrupted). That might explain the errors you are getting with ffmpeg

**Comment by gavinbeatty** [comment]
Thanks @tcurdt, I detect codecs properly now, and will fix to only try to "correct" profile on h264 shortly. Hopefully the corrupted HEVC/h265 files were not caused by that bug.
