### ISSUE TITLE
Python 3 support and new release

### ISSUE THREAD

**Issue by iMichka** [gavinbeatty/mkvtomp4#15]
Hi. Homebrew maintainer here (Homebrew is a package manager for mac, linux and windows). I wanted to ask what the status is for Python 3 support?

We are going through the list of Python 2 libraries, see https://github.com/Homebrew/homebrew-core/issues/47050.

Any timeline for proper Python 3 support?

**Comment by gavinbeatty** [comment]
It supports python 3 currently in master, so I’ll make a release.

**Comment by gavinbeatty** [comment]
@iMichka Tagged 2.0 and published to pypi

**Comment by iMichka** [comment]
Thanks, it worked! We updated the package here on our side: https://github.com/Homebrew/homebrew-core/pull/48328
